### ISSUE TITLE
Use xp_tracker page and deprecate display

### ISSUE THREAD

**Issue by InfAmelia** [InfAmelia/dnd_helper#1]

**Comment by byendan** [comment]
I'm thinking of how we could get rid of the displays model, and make it more specific to xp, since the values are xp_min, xp_max, and if my pull request goes through level. This doesn't seem like it could be generic to the point of being called displays. 

My thought on how to structure the models would be
- Party
  - Players
  - Level
  - CurrentXP
  - CurrentLocation/Map

So party has many players, has a map, and stores a level and currentXP itself
I'm assuming the table is the DM, which would have a party. 

Back to the xp tracker, I think it should be one of the views accessed from the party controller. We could also have a public view, where we could switch from xp tracker to map without reloading the page by loading all of the data when you view the public party page.
